services:
  db:
    image: postgres
    env_file:
      - .env
    ports:
      - 6500:${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $POSTGRES_USER'"]
      interval: 3s
      retries: 10

  api:
    restart: always
    build: ./api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  webapp:
    restart: always
    build: ./webapp
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./webapp/src:/app/src:Z
      - ./webapp/public:/app/public:Z

  dcdn:
    restart: always
    build: ./dcdn
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      POSTGRES_DB: bountydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - 9090:8080
    depends_on:
      - db

volumes:
  db:
