services:
  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${DB_PWD}
      - POSTGRES_USER=${DB_USER}
    ports:
      - 6500:${DB_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U $DB_USER'"]
      interval: 3s
      retries: 10

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:${RABBITMQ_PORT}"  # AMQP protocol port
      - "15672:${RABBITMQ_MANAGEMENT_PORT}" # Management UI
    env_file:
      - .env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia  # Ensure persistence
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      retries: 5
      start_period: 20s

  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - db

  wui:
    build: ./wui
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - api
    volumes:
      - ./wui/src:/app/src:Z
      - ./wui/public:/app/public:Z

  dcdn:
    build: ./dcdn
    ports:
      - "3001:3001"
    depends_on:
      - db
      - api
    env_file:
      - .env

  redis:
    image: redis:6.0.9
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - 9090:8080
    depends_on:
      - db

volumes:
  db:
  rabbitmq_data: