version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bountydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  backend:
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db
        #  frontend:
        #    build: ./front
        #    ports:
        #      - "80:80"
        #    depends_on:
        #      - backend

