version: '3.8'
services:
  db:
    restart: always
    image: postgres
    volumes:
      - ./db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bountydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  
  api:
    restart: always
    build: ./api
    ports:
      - "8080:8080"
    depends_on:
      - db

  web:
    restart: always
    build: ./front
    ports:
      - "3000:3000"
    depends_on:
      - api
